title: Lotes' lab
description: This is my blog. There are many blogs, but this blog is mine.
show_downloads: false
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - superscript
    - with_to_data
google_analytics:
exclude:
  - README.md
  - index.md