title: Lotes' lab
description: This is my blog. There are many blogs, but this blog is mine.
show_downloads: false
markdown: kramdown
google_analytics:
exclude:
  - README.md
  - index.md
kramdown:
  input: GFM
  hard_wrap: false